# Importing libraries 

In [2]:
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression as LR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import preprocessing

# Data Visualization

In [3]:
df = pd.read_csv('/content/drive/My Drive/AI/Deepankar Kansal - Data for AI-Assignment-3 - Sheet1.csv')
df

ID Gender  ... openess_to_experience  High-Salary
0     203097      f  ...               -0.4455            1
1     579905      m  ...                0.8637            1
2     810601      f  ...                0.6721            1
3     267447      m  ...               -0.9194            1
4     343523      m  ...               -0.1295            0
...      ...    ...  ...                   ...          ...
3993   47916      m  ...               -0.9194            0
3994  752781      f  ...               -0.0943            0
3995  355888      m  ...               -0.7615            1
3996  947111      f  ...               -0.0943            0
3997  324966      f  ...               -0.6035            1

[3998 rows x 34 columns]

In [4]:
data = df.iloc[:,:].values
print(data)

[[203097 'f' '1990-02-19 00:00:00' ... 1.3549 -0.4455 1]
 [579905 'm' '1989-10-04 00:00:00' ... -0.1076 0.8637 1]
 [810601 'f' '1992-08-03 00:00:00' ... -0.8682 0.6721 1]
 ...
 [355888 'm' '1991-07-03 00:00:00' ... -1.3184 -0.7615 1]
 [947111 'f' '1992-03-20 00:00:00' ... -0.3612 -0.0943 0]
 [324966 'f' '1991-02-26 00:00:00' ... 1.3255299999999999 -0.6035 1]]


In [5]:
data.shape

(3998, 34)

In [6]:
le = LabelEncoder()

In [7]:
print(np.unique(data[:,1]))

['f' 'm']


In [8]:
print(np.unique(data[:,7]))

[' board of intermediate' ' upboard' '0' 'ahsec' 'aissce'
 'aligarh muslim university' 'all india board' 'amravati divisional board'
 'andhpradesh board of intermediate education' 'andhra board'
 'andhra pradesh' 'andhra pradesh board of secondary education'
 'andhra pradesh state board' 'ap board'
 'ap board for intermediate education' 'ap intermediate board' 'apbie'
 'apbsc' 'apsb' 'aurangabad board' 'baord of intermediate education'
 'bciec,patna' 'bice' 'bie' 'bieap' 'biec' 'biec patna' 'biec, patna'
 'biec,patna' 'biec-patna' 'bihar' 'bihar board'
 'bihar intermediate education council'
 'bihar intermediate education council, patna'
 'bihar school examination board patna'
 'board fo intermediate education, ap'
 'board of high school and intermediate education uttarpradesh'
 'board of higher secondary examination, kerala'
 'board of higher secondary orissa' 'board of intermeadiate education'
 'board of intermediate' 'board of intermediate ap'
 'board of intermediate education'
 'bo

In [9]:
print(np.unique(data[:,4]))

['0' 'aisse' 'andhra pradesh board ssc' 'andhra pradesh state board'
 'anglo indian' 'ap state board' 'ap state board for secondary education'
 'apsche' 'apssc' 'aurangabad board' 'bharathi matriculation school'
 'bihar' 'bihar board' 'bihar examination board, patna'
 'bihar school examination board' 'bihar school examination board patna'
 'bihar secondary education board,patna' 'biharboard'
 'board of  secondary education'
 'board of high school and intermediate education uttarpradesh'
 'board of intermediate education' 'board of school education harayana'
 'board of school education haryana'
 'board of school education uttarakhand'
 'board of secendary education orissa' 'board of secondaray education'
 'board of secondary education'
 'board of secondary education (bse) orissa'
 'board of secondary education - andhra pradesh'
 'board of secondary education orissa'
 'board of secondary education rajasthan'
 'board of secondary education(bse) orissa'
 'board of secondary education, andh

In [10]:
print(np.unique(data[:,10]))

['B.Tech/B.E.' 'M.Sc. (Tech.)' 'M.Tech./M.E.' 'MCA']


In [11]:
print(np.unique(data[:,11]))

['aeronautical engineering' 'applied electronics and instrumentation'
 'automobile/automotive engineering' 'biomedical engineering'
 'biotechnology' 'ceramic engineering' 'chemical engineering'
 'civil engineering' 'computer and communication engineering'
 'computer application' 'computer engineering' 'computer networking'
 'computer science' 'computer science & engineering'
 'computer science and technology'
 'control and instrumentation engineering'
 'electrical and power engineering' 'electrical engineering' 'electronics'
 'electronics & instrumentation eng' 'electronics & telecommunications'
 'electronics and communication engineering'
 'electronics and computer engineering'
 'electronics and electrical engineering'
 'electronics and instrumentation engineering' 'electronics engineering'
 'embedded systems technology' 'industrial & management engineering'
 'industrial & production engineering' 'industrial engineering'
 'information & communication technology' 'information science'


In [12]:
print(np.unique(data[:,15]))

['Andhra Pradesh' 'Assam' 'Bihar' 'Chhattisgarh' 'Delhi' 'Goa' 'Gujarat'
 'Haryana' 'Himachal Pradesh' 'Jammu and Kashmir' 'Jharkhand' 'Karnataka'
 'Kerala' 'Madhya Pradesh' 'Maharashtra' 'Meghalaya' 'Orissa' 'Punjab'
 'Rajasthan' 'Sikkim' 'Tamil Nadu' 'Telangana' 'Union Territory'
 'Uttar Pradesh' 'Uttarakhand' 'West Bengal']


# Data Preprocessing

## 1. Label Encoding

In [13]:
clm = [1, 4, 7, 10, 11, 15]
for i in clm:
  data[:,i] = le.fit_transform(data[:,i])
  print(np.unique(data[:,i]))

[0 1]
[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51
 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99
 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 27

In [14]:
print(data)

[[203097 0 '1990-02-19 00:00:00' ... 1.3549 -0.4455 1]
 [579905 1 '1989-10-04 00:00:00' ... -0.1076 0.8637 1]
 [810601 0 '1992-08-03 00:00:00' ... -0.8682 0.6721 1]
 ...
 [355888 1 '1991-07-03 00:00:00' ... -1.3184 -0.7615 1]
 [947111 0 '1992-03-20 00:00:00' ... -0.3612 -0.0943 0]
 [324966 0 '1991-02-26 00:00:00' ... 1.3255299999999999 -0.6035 1]]


## 2. DOB to Age

In [15]:
for i in range(data.shape[0]):
  atr = data[i][2].split(' ')
  date_dt2 = datetime.strptime(atr[0], '%Y-%m-%d')
  td = datetime.today()
  diff = td - date_dt2
  age = float(np.around(diff.days/365, 3))
  data[i][2] = age

In [16]:
print(data)

[[203097 0 30.775 ... 1.3549 -0.4455 1]
 [579905 1 31.153 ... -0.1076 0.8637 1]
 [810601 0 28.321 ... -0.8682 0.6721 1]
 ...
 [355888 1 29.408 ... -1.3184 -0.7615 1]
 [947111 0 28.693 ... -0.3612 -0.0943 0]
 [324966 0 29.756 ... 1.3255299999999999 -0.6035 1]]


In [17]:
df = pd.DataFrame(data)
df

0  1       2      3    4   ...      29      30       31      32 33
0     203097  0  30.775   84.3   43  ...  0.8128  0.5269   1.3549 -0.4455  1
1     579905  1  31.153   85.4   60  ...  0.3789  1.2396  -0.1076  0.8637  1
2     810601  0  28.321     85   60  ...  1.7109  0.1637  -0.8682  0.6721  1
3     267447  1  30.984   85.6   60  ...  0.3448  -0.344  -0.4078 -0.9194  1
4     343523  1  29.753     78   60  ... -0.2793 -1.0697  0.09163 -0.1295  0
...      ... ..     ...    ...  ...  ...     ...     ...      ...     ... ..
3993   47916  1  33.627  52.09   60  ...  0.3448  0.2366   0.6498 -0.9194  0
3994  752781  0  28.255     90  224  ...  0.8784  0.9322   0.7798 -0.0943  0
3995  355888  1  29.408  81.86   50  ... -1.5273 -1.5051  -1.3184 -0.7615  1
3996  947111  0  28.693  78.72  224  ...  0.0459 -0.4511  -0.3612 -0.0943  0
3997  324966  0  29.756   70.6   60  ... -0.2793 -0.6343  1.32553 -0.6035  1

[3998 rows x 34 columns]

## 3. Removing Un-necessary Columns

In [18]:
new_data = np.delete(data, 0, 1)
print(new_data)

[[0 30.775 84.3 ... 1.3549 -0.4455 1]
 [1 31.153 85.4 ... -0.1076 0.8637 1]
 [0 28.321 85.0 ... -0.8682 0.6721 1]
 ...
 [1 29.408 81.86 ... -1.3184 -0.7615 1]
 [0 28.693 78.72 ... -0.3612 -0.0943 0]
 [0 29.756 70.6 ... 1.3255299999999999 -0.6035 1]]


In [19]:
to_del = [4,5,7,8,9,13,14,15,16]
min = 1
for i in to_del:
  new_data = np.delete(new_data, i-min, 1)
  min+=1
# print(new_data)

In [20]:
df1 = pd.DataFrame(new_data)
df1

0       1      2      3  4   ...      19      20       21      22 23
0     0  30.775   84.3   95.8  0  ...  0.8128  0.5269   1.3549 -0.4455  1
1     1  31.153   85.4     85  0  ...  0.3789  1.2396  -0.1076  0.8637  1
2     0  28.321     85   68.2  0  ...  1.7109  0.1637  -0.8682  0.6721  1
3     1  30.984   85.6   83.6  0  ...  0.3448  -0.344  -0.4078 -0.9194  1
4     1  29.753     78   76.8  0  ... -0.2793 -1.0697  0.09163 -0.1295  0
...  ..     ...    ...    ... ..  ...     ...     ...      ...     ... ..
3993  1  33.627  52.09   55.5  0  ...  0.3448  0.2366   0.6498 -0.9194  0
3994  0  28.255     90     93  0  ...  0.8784  0.9322   0.7798 -0.0943  0
3995  1  29.408  81.86   65.5  0  ... -1.5273 -1.5051  -1.3184 -0.7615  1
3996  0  28.693  78.72  69.88  0  ...  0.0459 -0.4511  -0.3612 -0.0943  0
3997  0  29.756   70.6     68  0  ... -0.2793 -0.6343  1.32553 -0.6035  1

[3998 rows x 24 columns]

In [21]:
X = new_data[:,:-1]
y = new_data[:,-1]
print(X.shape,y.shape)

(3998, 23) (3998,)


## 4. Scaling

In [22]:
sc = StandardScaler()
X = sc.fit_transform(X)

# Models

In [23]:
y = y.astype('int')
max_ac = [0]*4
random_state = [0]*4
test_size = [0.1, 0.2, 0.3, 0.4]
for ts in test_size:
  for i in range(120):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = ts, random_state=i)
    
    clf = LR()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    ac1 = accuracy_score(y_test, y_pred)
    
    if (max_ac[0] < ac1 and ts == 0.1):
      max_ac[0] = ac1
      random_state[0] = i
    if (max_ac[1] < ac1 and ts == 0.2):
      max_ac[1] = ac1
      random_state[1] = i
    if (max_ac[2] < ac1 and ts == 0.3):
      max_ac[2] = ac1
      random_state[2] = i
    if (max_ac[3] < ac1 and ts == 0.4):
      max_ac[3] = ac1
      random_state[3] = i

# Normalized Accuracies and Confusion Matrix and Class-wise Accuracy 

In [26]:
def checking_accuracy_classwise(y_test,y_pred,class_):
  n=0
  j=0
  i=0
  while (j<y_test.size): #test_accuracy
    if (y_pred[j] == y_test[j] and y_pred[j] == class_):
      n += 1
      i += 1
    elif (y_test[j] == class_):
      i += 1
    j+=1
  accu = n/i
  return accu

In [28]:
ac_max = 0
split = 0
cm_max = 0
i=0
for ts in test_size:
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = ts, random_state=random_state[i])
  clf = LR()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  ac1 = accuracy_score(y_test, y_pred)
  ac_0 = checking_accuracy_classwise(y_test, y_pred, 0)
  ac_1 = checking_accuracy_classwise(y_test, y_pred, 1)
  cm = confusion_matrix(y_test, y_pred)
  if (ac1>ac_max):
    ac_max = ac1
    split = ts
    cm_max = cm
  print('\033[1m'+"Normalized Accuracy on split of {0:d}/{1:d} is {2:.2f}%".format(int(100-(ts*100)),int(ts*100),ac1*100))
  print('Accuracy for class 0 is {0:.2f}% \nAccuracy for class 1 is {1:.2f}%'.format(ac_0*100,ac_1*100))
  print("Confusion matrix for the same is \n",cm,"\n\n")
  i+=1

Normalized Accuracy on split of 90/10 is 77.50%
Accuracy for class 0 is 70.27% 
Accuracy for class 1 is 83.72%
Confusion matrix for the same is 
 [[130  55]
 [ 35 180]] 


Normalized Accuracy on split of 80/20 is 74.38%
Accuracy for class 0 is 72.00% 
Accuracy for class 1 is 76.22%
Confusion matrix for the same is 
 [[252  98]
 [107 343]] 


Normalized Accuracy on split of 70/30 is 74.08%
Accuracy for class 0 is 72.81% 
Accuracy for class 1 is 75.11%
Confusion matrix for the same is 
 [[391 146]
 [165 498]] 


Normalized Accuracy on split of 60/40 is 74.25%
Accuracy for class 0 is 71.43% 
Accuracy for class 1 is 76.73%
Confusion matrix for the same is 
 [[535 214]
 [198 653]] 




In [ ]:
print('\033[1m'+'Maximum normalized accuracy achieved is {2:.2f}% at split of {0:d}/{1:d}'.format(int(100-(split*100)),int(split*100),ac_max*100))
print("Confusion matrix for the same is \n",cm_max)

Maximum normalized accuracy achieved is 77.50% at split of 90/10
Confusion matrix for the same is 
 [[130  55]
 [ 35 180]]
